import "./globals.css";
import { Inter } from "next/font/google";
import NavDesktop from "./components/nav-desktop";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
        <NavDesktop />
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
