import "./globals.css";
import { Inter } from "next/font/google";
import NavDesktop from "./components/nav-desktop";
import MobileNav from "./components/Mobile-Nav";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fermoy Dental Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div>
          <NavDesktop />
          <MobileNav />
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
